spring.application.name=NDI-Project

spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

# NDI
ndi.auth.url=https://staging.bhutanndi.com/authentication/v1/authenticate
ndi.verifier.url=https://demo-client.bhutanndi.com/verifier/v1/proof-request
ndi.client.id=3tq7ho23g5risndd90a76jre5f
ndi.client.secret=111rvn964mucumr6c3qq3n2poilvq5v92bkjh58p121nmoverquh
ndi.webhook.url=https://capacity-blemish-fondly.ngrok-free.dev/ndi/webhook