spring.application.name=NDI-Project

spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

# NDI
 ndi.auth.url=https://staging.bhutanndi.com/authentication/v1/authenticate
 ndi.verifier.url=https://demo-client.bhutanndi.com/verifier/v1/proof-request
 ndi.client.id=3tq7ho23g5risndd90a76jre5f
 ndi.client.secret=111rvn964mucumr6c3qq3n2poilvq5v92bkjh58p121nmoverquh


 ############################################
 # NDI VERIFIER
 ############################################
 ndi.verifier.proof.url=https://demo-client.bhutanndi.com/verifier/v1/proof-request
 ndi.verifier.status.url=https://demo-client.bhutanndi.com/verifier/v1/proof-request?threadId=
 ndi.verifier.presentation.url=https://demo-client.bhutanndi.com/verifier/v1/proof-presentation?threadId=


 ############################################
 # NDI WEBHOOK SERVICE
 ############################################
 ndi.webhook.register.url=https://demo-client.bhutanndi.com/webhook/v1/register
 ndi.webhook.subscribe.url=https://demo-client.bhutanndi.com/webhook/v1/subscribe
 ndi.webhook.unsubscribe.url=https://demo-client.bhutanndi.com/webhook/v1/unsubscribess


 ############################################
 # YOUR WEBHOOK CONFIG
 ############################################
 ndi.webhook.id=rtp_webhook_109_s_dev_0101

 # ? Your ngrok URL + endpoint
 ndi.webhook.url=https://sheri-gildable-hendrix.ngrok-free.dev/webhook

 # ? OAuth2 v2 (FIXED TOKEN ? simplest)
 ndi.webhook.auth.type=OAuth2
 ndi.webhook.auth.version=v2

 # This is ANY random secure string (NDI will send it back)
 ndi.webhook.fixed.token=thisIsWebhookToken0120121

 ndi.foundation.schema=https://dev-schema.ngotag.com/schemas/c7952a0a-e9b5-4a4b-a714-1e5d0a1ae076
 ndi.permanent.schema=https://dev-schema.ngotag.com/schemas/e3b606d0-e477-4fc2-b5ab-0adc4bd75c54
